//
//  MatchProfilePresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 21/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MatchProfilePresentationProtocol {
    func presentSomething()
}

class MatchProfilePresenter: MatchProfilePresentationProtocol {
    weak var viewController: MatchProfileProtocol?
    var interactor: MatchProfileInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
