//
//  NewMobileNumberPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 29/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMobileNumberPresentationProtocol {
    func callResendOTPAPI(vCountryCode: String, vPhone: String)
    func getResendOTPResponse(response : CommonResponse)
}

class NewMobileNumberPresenter: NewMobileNumberPresentationProtocol {
    weak var viewController: NewMobileNumberProtocol?
    var interactor: NewMobileNumberInteractorProtocol?
    
    // MARK: Present something
    func callResendOTPAPI(vCountryCode: String, vPhone: String) {
        self.interactor?.callResendOTPAPI(vCountryCode: vCountryCode, vPhone: vPhone)
    }
    func getResendOTPResponse(response : CommonResponse) {
        self.viewController?.getResendOTPResponse(response: response)
    }
}
