//
//  PreviewPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 04/06/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreviewPresentationProtocol {
    func callPostStoryAPI(obj : PostData)
    func getPostStoryResponse(response: CommonResponse)
}

class PreviewPresenter: PreviewPresentationProtocol {
    weak var viewController: PreviewProtocol?
    var interactor: PreviewInteractorProtocol?
    
    // MARK: Present something
    
    func callPostStoryAPI(obj : PostData){
        self.interactor?.addPostAPICall(with: obj)
    }
    func getPostStoryResponse(response: CommonResponse) {
        self.viewController?.getPostStoryResponse(response: response)
    }
}
