//
//  TabbarInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 17/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabbarInteractorProtocol {
    func callStoryListAPI()
}

protocol TabbarDataStore {
    //var name: String { get set }
}

class TabbarInteractor: TabbarInteractorProtocol, TabbarDataStore {
    var presenter: TabbarPresentationProtocol?
    //var name: String = ""
    
    func callStoryListAPI() {
        //        LoaderView.sharedInstance.showLoader()
        MediaAPI.listStory(nonce: authToken.nonce, timestamp: authToken.timeStamp, token: authToken.token, authorization: UserDataModel.authorization, _id: 0) { (response, error) in
            
            //            delay(0.2) {
            //                LoaderView.sharedInstance.hideLoader()
            //            }
            if response?.responseCode == 200 {
                self.presenter?.getStoryListResponse(response: response!)
            } else if response?.responseCode == 203 {
                AppSingleton.sharedInstance().logout()
                AppSingleton.sharedInstance().showAlert((response?.responseMessage!)!, okTitle: "OK")
            } else if response?.responseCode == 400 {
                self.presenter?.getStoryListResponse(response: response!)
            }  else {
                if error != nil {
                    AppSingleton.sharedInstance().showAlert(kSomethingWentWrong, okTitle: "OK")
                } else {
                    self.presenter?.getStoryListResponse(response: response!)
                }
            }
        }
    }
}
