//
//  ForgotPasswordInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 20/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordInteractorProtocol {
    func callForgotPasswordAPI(email : String)
}

protocol ForgotPasswordDataStore {
    //var name: String { get set }
}

class ForgotPasswordInteractor: ForgotPasswordInteractorProtocol, ForgotPasswordDataStore {
    var presenter: ForgotPasswordPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callForgotPasswordAPI(email : String) {
        DefaultLoaderView.sharedInstance.showLoader()
        UserAPI.forgotPassword(nonce: authToken.nonce, timestamp: Int(authToken.timeStamps)!, token: authToken.token, language: APPLANGUAGE.english, vEmail: email) { (response, error) in
            
            delay(0.2) {
                DefaultLoaderView.sharedInstance.hideLoader()
            }
            
            if response?.responseCode == 200 {
                self.presenter?.getForgotPasswordResponse(response: response!)
            } else if response?.responseCode == 203 {
                AppSingleton.sharedInstance().logout()
                AppSingleton.sharedInstance().showAlert((response?.responseMessage!)!, okTitle: "OK")
            }  else {
                if error != nil {
                    AppSingleton.sharedInstance().showAlert(kSomethingWentWrong, okTitle: "OK")
                } else {
                    AppSingleton.sharedInstance().showAlert((response?.responseMessage!)!, okTitle: "OK")
                }
            }
        }
    }
}
