//
//  ChangePasswordPresenter.swift
//  Basecode
//
//  Created by SOTSYS203 on 01/03/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordPresentationProtocol {
    func callChangePasswordRequest(changePasswordParam: Dictionary<String, String>)
    func getChangePasswordResponse(response : BaseModel?)
    
}

class ChangePasswordPresenter: ChangePasswordPresentationProtocol {
    weak var viewController: ChangePasswordProtocol?
    var interactor: ChangePasswordInteractorProtocol?
    
    func callChangePasswordRequest(changePasswordParam: Dictionary<String, String>) {
        self.interactor?.callChangePasswordApi(params: changePasswordParam)
    }
    
    func getChangePasswordResponse(response : BaseModel?) {
        self.viewController?.getUpdateView(objModel: response)
    }
}
