//
//  ChangePasswordInteractor.swift
//  Basecode
//
//  Created by SOTSYS203 on 01/03/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordInteractorProtocol {
    func callChangePasswordApi(params : Dictionary<String, String>)
}

protocol ChangePasswordDataStore {
    //var name: String { get set }
}

class ChangePasswordInteractor: ChangePasswordInteractorProtocol, ChangePasswordDataStore {
    var presenter: ChangePasswordPresentationProtocol?
    //var name: String = ""
    
    func callChangePasswordApi(params : Dictionary<String, String>) {
        SOService.callAPI(SOAPI.changePassword(params: params)) { (code, error, result) in
            if code == 1 {
                self.presenter?.getChangePasswordResponse(response: nil)
            } else {
                self.presenter?.getChangePasswordResponse(response: nil)
            }
        }
    }
}
