//
//  ChangePasswordViewController.swift
//  Basecode
//
//  Created by SOTSYS203 on 01/03/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordProtocol: class {
    func getUpdateView(objModel : BaseModel?)
}

class ChangePasswordViewController: UIViewController, ChangePasswordProtocol {
    //var interactor : ChangePasswordInteractorProtocol?
    var presenter : ChangePasswordPresentationProtocol?
    
    //Outlets
    @IBOutlet weak var txtOldPassword : UITextField?
    @IBOutlet weak var txtNewPassword : UITextField?
    @IBOutlet weak var txtConfirmPassword : UITextField?
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ChangePasswordInteractor()
        let presenter = ChangePasswordPresenter()
        
        //View Controller will communicate with only presenter
        viewController.presenter = presenter
        //viewController.interactor = interactor
        
        //Presenter will communicate with Interector and Viewcontroller
        presenter.viewController = viewController
        presenter.interactor = interactor
        
        //Interactor will communucate with only presenter.
        interactor.presenter = presenter
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    @IBAction func actionChangePassword() {
        let param = RequestParameter.sharedInstance().changePasswordParam(newPassword: (txtNewPassword?.text)!, oldPassword: (txtOldPassword?.text)!)
        self.presenter?.callChangePasswordRequest(changePasswordParam: param)
    }
    
    func getUpdateView(objModel : BaseModel?)  {
        
    }

    
    @IBAction func actionBack() {
        self.popVC()
    }

}
