//
//  MenuPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 20/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuPresentationProtocol {
    func callSignoutAPI()
    func getSignoutResponse(response : UserAuthResponse)
    
    func callUpdateLocationAPI(fLatitude : String, fLongitude : String)
    func getLocationUpdateResponse(response : UserAuthResponse)
    
    func callPushStatusAPI(tiIsAcceptPush : String)
    func getPushStatusResponse(response : UserAuthResponse)
}

class MenuPresenter: MenuPresentationProtocol {
    weak var viewController: MenuProtocol?
    var interactor: MenuInteractorProtocol?
    
    // MARK: Present something
    func callSignoutAPI() {
        self.interactor?.callSignoutAPI()
    }
    
    func getSignoutResponse(response : UserAuthResponse){
        self.viewController?.getSignOutResponse(response : response)
    }
    
    func callUpdateLocationAPI(fLatitude : String, fLongitude : String){
        self.interactor?.callUpdateLocationAPI(fLatitude: fLatitude, fLongitude: fLongitude)
    }
    
    func getLocationUpdateResponse(response : UserAuthResponse){
        self.viewController?.getLocationUpdateResponse(response: response)
    }
    
    func callPushStatusAPI(tiIsAcceptPush : String){
        self.interactor?.callPushStatusAPI(tiIsAcceptPush : tiIsAcceptPush)
    }
    
    func getPushStatusResponse(response : UserAuthResponse){
        self.viewController?.getPushStatusResponse(response : response)
    }
}
