//
//  UserProfilePresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 20/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfilePresentationProtocol {
    func presentSomething()
}

class UserProfilePresenter: UserProfilePresentationProtocol {
    weak var viewController: UserProfileProtocol?
    var interactor: UserProfileInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
