//
//  HomePresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 20/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationProtocol {
    func gotoMatchVC()
}

class HomePresenter: HomePresentationProtocol {
    weak var viewController: HomeProtocol?
    var interactor: HomeInteractorProtocol?
    
    // MARK: Present something
    func gotoMatchVC() {
        let controller = GeekMeets_StoryBoard.Dashboard.instantiateViewController(withIdentifier: GeekMeets_ViewController.MatchScreen)
        controller.modalTransitionStyle = .crossDissolve
        controller.modalPresentationStyle = .overCurrentContext
        
        if let view = self.viewController as? UIViewController
        {
            view.presentVC(controller)
            //            view.pushVC(controller)
        }
    }
}
