//
//  AccountSettingPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 23/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com

import UIKit

protocol AccountSettingPresentationProtocol {
    func presentSomething()
}

class AccountSettingPresenter: AccountSettingPresentationProtocol {
    weak var viewController: AccountSettingProtocol?
    var interactor: AccountSettingInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
