//
//  CommonPagesViewController.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 23/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//enum CommonModelData {
//
//    case Tips
//    case Terms
//    case Privacy
//    case About
//    case Licenses
//
//    var Title : String {
//        switch self {
//        case .Tips:
//            return "Tips"
//        case .Terms:
//            return "Terms & Conditions"
//        case .Privacy:
//            return "Privacy Policy"
//        case .About:
//            return "About Us"
//        case .Licenses:
//            return "Licenses"
//        }
//    }
//
//
//}
protocol CommonPagesProtocol: class {
}

class CommonPagesViewController: UIViewController, CommonPagesProtocol {
    //var interactor : CommonPagesInteractorProtocol?
    var presenter : CommonPagesPresentationProtocol?
    
    @IBOutlet weak var lblScreenTitle: UILabel!
    @IBOutlet weak var descView: UITextView!
    
    var objCommonData : [CommonCellModel] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CommonPagesInteractor()
        let presenter = CommonPagesPresenter()
        
        //View Controller will communicate with only presenter
        viewController.presenter = presenter
        //viewController.interactor = interactor
        
        //Presenter will communicate with Interector and Viewcontroller
        presenter.viewController = viewController
        presenter.interactor = interactor
        
        //Interactor will communucate with only presenter.
        interactor.presenter = presenter
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setData()
    }
    
    
    func setData(){
        self.objCommonData = [CommonCellModel(title: "Tips", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", isDescAvailable: true)]
        
        self.lblScreenTitle.text = objCommonData[0].title
        self.descView.text = objCommonData[0].description
    }
    @IBAction func btnBackAction(_ sender: UIButton) {
        self.popVC()
    }
}

