//
//  SelectCategoriesPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 24/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectCategoriesPresentationProtocol {
    func presentSomething()
    func callQuestionnaireRequest()
    func getQuestionnaireResponse(userData : [QuestionnaireModel]?)
    func actionContinue()
    func actionSkip()
}

class SelectCategoriesPresenter: SelectCategoriesPresentationProtocol {
    weak var viewController: SelectCategoriesProtocol?
    var interactor: SelectCategoriesInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
  func callQuestionnaireRequest() {
            self.interactor?.callQuestionnaireApi()
         }
         
         func getQuestionnaireResponse(userData : [QuestionnaireModel]?){
           self.viewController?.displayQuesionsData(Data: userData!)
         }
       
       
       
         func actionContinue() {
             let controller = GeekMeets_StoryBoard.Dashboard.instantiateViewController(withIdentifier: GeekMeets_ViewController.TabbarScreen)
             if let view = self.viewController as? UIViewController
             {
                 view.pushVC(controller)
             }
         }
         func actionSkip() {
                let controller = GeekMeets_StoryBoard.Dashboard.instantiateViewController(withIdentifier: GeekMeets_ViewController.TabbarScreen)
                if let view = self.viewController as? UIViewController
                {
                    view.pushVC(controller)
                }
            }
  }
