//
//  DiscoverySettingInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 23/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscoverySettingInteractorProtocol {
    func doSomething()
}

protocol DiscoverySettingDataStore {
    //var name: String { get set }
}

class DiscoverySettingInteractor: DiscoverySettingInteractorProtocol, DiscoverySettingDataStore {
    var presenter: DiscoverySettingPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething() {
        
    }
}
