//
//  AddPhotosPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 21/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPhotosPresentationProtocol {
    func callUserSignUpAPI(signParams : Dictionary<String, String>, photos : [NSDictionary])
    func getSignUpResponse(response : UserAuthResponse)
}

class AddPhotosPresenter: AddPhotosPresentationProtocol {
    weak var viewController: AddPhotosProtocol?
    var interactor: AddPhotosInteractorProtocol?
    
    func callUserSignUpAPI(signParams : Dictionary<String, String>, photos : [NSDictionary]) {
        self.interactor?.callUserSignUpAPI(signParams : signParams, photos : photos)
    }
    
    func getSignUpResponse(response : UserAuthResponse) {
        
        UserDataModel.currentUser = response.responseData
        
        let controller = GeekMeets_StoryBoard.LoginSignUp.instantiateViewController(withIdentifier: GeekMeets_ViewController.OTPEnter)
        if let view = self.viewController as? UIViewController
        {
            view.pushVC(controller)
        }
    }
}
