//
//  MessagesInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 21/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagesInteractorProtocol {
    func doSomething()
}

protocol MessagesDataStore {
    //var name: String { get set }
}

class MessagesInteractor: MessagesInteractorProtocol, MessagesDataStore {
    var presenter: MessagesPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething() {
        
    }
}
