//
//  SignUpInteractor.swift
//  Basecode
//
//  Created by SOTSYS203 on 19/02/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpInteractorProtocol {
    func callSignUpApi(params : Dictionary<String, Any>)
}

protocol SignUpDataStore {
    //var name: String { get set }
}

class SignUpInteractor: SignUpInteractorProtocol, SignUpDataStore {
    var presenter: SignUpPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callSignUpApi(params : Dictionary<String, Any>) {
                
//        UserAPI.signUp(nonce: authToken.nonce, timestamp: Int(authToken.timeStamp)!, token: authToken.token, tiIsSocialLogin: UserAPI.TiIsSocialLogin_signUp(rawValue: "0"), vEmail: <#T##String#>, vPassword: <#T##String#>, vCountryCode: <#T##String#>, vPhone: <#T##String#>, vName: <#T##String#>, dDob: <#T##String#>, tiAge: <#T##String#>, tiGender: <#T##UserAPI.TiGender_signUp#>, iCurrentStatus: <#T##UserAPI.ICurrentStatus_signUp#>, txCompanyDetail: <#T##String#>, txAbout: <#T##String#>, photos: <#T##String#>, vTimeOffset: <#T##String#>, vTimeZone: <#T##String#>, vDeviceToken: <#T##String#>, tiDeviceType: <#T##UserAPI.TiDeviceType_signUp#>, vDeviceName: <#T##String#>, vDeviceUniqueId: <#T##String#>, vApiVersion: <#T##String#>, vAppVersion: <#T##String#>, vOsVersion: <#T##String#>, vIpAddress: <#T##String#>) { (response, error) in
//            
//            
//        }
    }
}
