//
//  SelectAgeRangePresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 23/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectAgeRangePresentationProtocol {
    func presentSomething()
    func callQuestionnaireRequest()
    func getQuestionnaireResponse(userData : [QuestionnaireModel]?)
}

class SelectAgeRangePresenter: SelectAgeRangePresentationProtocol {
    func callQuestionnaireRequest() {
       self.interactor?.callQuestionnaireApi()
    }
    
    func getQuestionnaireResponse(userData : [QuestionnaireModel]?){
      self.viewController?.displayQuesionsData(Data: userData!)
    }
  
    weak var viewController: SelectAgeRangeProtocol?
    var interactor: SelectAgeRangeInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
