//
//  ForgotPasswordPresenter.swift
//  Basecode
//
//  Created by SOTSYS203 on 19/02/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPresentationProtocol {
    func presentSomething()
}

class ForgotPasswordPresenter: ForgotPasswordPresentationProtocol {
    weak var viewController: ForgotPasswordProtocol?
    var interactor: ForgotPasswordInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
