//
//  ForgotPasswordInteractor.swift
//  Basecode
//
//  Created by SOTSYS203 on 19/02/18.
//  Copyright (c) 2018 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordInteractorProtocol {
    func doSomething()
}

protocol ForgotPasswordDataStore {
    //var name: String { get set }
}

class ForgotPasswordInteractor: ForgotPasswordInteractorProtocol, ForgotPasswordDataStore {
    var presenter: ForgotPasswordPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething() {
        
    }
}
