//
//  OTPEnterPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 21/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTPEnterPresentationProtocol {
    func presentSomething()
    func actionVerifyOTP()
}

class OTPEnterPresenter: OTPEnterPresentationProtocol {
    weak var viewController: OTPEnterProtocol?
    var interactor: OTPEnterInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
    
    func actionVerifyOTP() {
        let controller = GeekMeets_StoryBoard.Questionnaire.instantiateViewController(withIdentifier: GeekMeets_ViewController.SelectAgeRange)
        if let view = self.viewController as? UIViewController
        {
            view.pushVC(controller)
        }
    }
}
