//
//  SignUpVCInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 17/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpVCInteractorProtocol {
    func doSomething()
}

protocol SignUpVCDataStore {
    //var name: String { get set }
}

class SignUpVCInteractor: SignUpVCInteractorProtocol, SignUpVCDataStore {
    var presenter: SignUpVCPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething() {
        
    }
}
