//
//  FirstCallPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 16/07/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstCallPresentationProtocol {
    func callStaticPageAPI()
    func getContentPageResponse(response:ContentPageResponse)
}

class FirstCallPresenter: FirstCallPresentationProtocol {
    weak var viewController: FirstCallProtocol?
    var interactor: FirstCallInteractorProtocol?
    
    // MARK: Present something
    func callStaticPageAPI() {
        self.interactor?.callStaticPageAPI()
    }
    
    func getContentPageResponse(response:ContentPageResponse){
        self.viewController?.getContentPageResponse(response: response)
    }
}
