//
//  NotificationListInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 15/05/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationListInteractorProtocol {
    func doSomething()
}

protocol NotificationListDataStore {
    //var name: String { get set }
}

class NotificationListInteractor: NotificationListInteractorProtocol, NotificationListDataStore {
    var presenter: NotificationListPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething() {
        
    }
}
