//
//  TopGeeksPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 23/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopGeeksPresentationProtocol {
    func callCreateGeeksAPI(param : Dictionary<String, String>)
    func getGeeksResponse(response : BoostGeekResponse)
    
    func callActiveGeeksAPI()
}

class TopGeeksPresenter: TopGeeksPresentationProtocol {
    weak var viewController: TopGeeksProtocol?
    var interactor: TopGeeksInteractorProtocol?
    
    // MARK: Present something
    func callCreateGeeksAPI(param : Dictionary<String, String>) {
        self.interactor?.callCreateGeeksAPI(param: param)
    }
    
    func getGeeksResponse(response : BoostGeekResponse){
        self.viewController?.getGeeksResponse(response : response)
    }
    
    func callActiveGeeksAPI(){
        
    }
}
