//
//  AddEditPhotosPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 29/09/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddEditPhotosPresentationProtocol {
    func callAddPhotosAPI(param : Dictionary<String, String>, images : [NSDictionary])
    func getProfileResponse(response : UserAuthResponse)
}

class AddEditPhotosPresenter: AddEditPhotosPresentationProtocol {
    weak var viewController: AddEditPhotosProtocol?
    var interactor: AddEditPhotosInteractorProtocol?
    
    // MARK: Present something
    func callAddPhotosAPI(param : Dictionary<String, String>, images : [NSDictionary]){
        if images.count > 0 {
            self.interactor?.uploadImgToS3(with : param, images: images)
        } else {
            self.interactor?.callAddPhotosAPI(param : param)
        }
    }
    
    func getProfileResponse(response : UserAuthResponse){
        self.viewController?.getProfileResponse(response : response)
    }
}
