//
//  Interest_PreferenceViewController.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 20/05/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Interest_PreferenceProtocol: class {
}

class Interest_PreferenceViewController: UIViewController, Interest_PreferenceProtocol {
    //var interactor : Interest_PreferenceInteractorProtocol?
    var presenter : Interest_PreferencePresentationProtocol?
    
    @IBOutlet weak var tblInterestList: UITableView!
    @IBOutlet weak var lblTitle: UILabel!
    
    var header_title : String = ""
    var objDiscoverData : [CommonCellModel] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = Interest_PreferenceInteractor()
        let presenter = Interest_PreferencePresenter()
        
        //View Controller will communicate with only presenter
        viewController.presenter = presenter
        //viewController.interactor = interactor
        
        //Presenter will communicate with Interector and Viewcontroller
        presenter.viewController = viewController
        presenter.interactor = interactor
        
        //Interactor will communucate with only presenter.
        interactor.presenter = presenter
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.registerTableViewCell()
    }
    
    func registerTableViewCell(){
        
        self.lblTitle.text = header_title
        self.tblInterestList.register(UINib.init(nibName: Cells.CommonTblListCell, bundle: Bundle.main), forCellReuseIdentifier: Cells.CommonTblListCell)
        
    }
    
    @IBAction func btnBackAction(_ sender: UIButton) {
        self.popVC()
    }
}

extension Interest_PreferenceViewController : UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.objDiscoverData.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: Cells.CommonTblListCell)
        cell?.selectionStyle = .none
        if let cell = cell as? CommonTblListCell {
            
            let data = self.objDiscoverData[indexPath.row]
            
            cell.lblTitle.text = data.title
            cell.lblDesc.text = data.description
        }
        return cell!
    }
    
  /*  func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if let cell = cell as? CommonTblListCell {
            
            let data = self.objDiscoverData[indexPath.row]
            
            cell.lblTitle.text = data.title
            cell.lblDesc.text = data.description
        }
    }
    */
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let data = self.objDiscoverData[indexPath.row]
        if data.isDescAvailable {
            return UITableView.automaticDimension
        } else {
            return 70
        }
    }
    
     func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let index = indexPath.row
        let queVC = GeekMeets_StoryBoard.Questionnaire.instantiateViewController(withIdentifier: GeekMeets_ViewController.SelectAgeRange) as? SelectAgeRangeViewController
        queVC?.isFromSignUp = false
        queVC?.interest_delegate = self
        if index == 0 {
            queVC?.index = 1
        } else if index == 1 {
            queVC?.index = 5
        } else if index == 2 {
            queVC?.index = 12
        } else if index == 3 {
            queVC?.index = 18
        } else {
            queVC?.index = 20
        }
        self.pushVC(queVC!)
    }
}


extension Interest_PreferenceViewController : SelectInterestAgeGenderDelegate {
    func getSelectedValue(index: Int, data: String) {
        if index == 1 {
            self.objDiscoverData[0].description = data
        } else if index == 5 {
            self.objDiscoverData[1].description = data
        } else if index == 12 {
            self.objDiscoverData[2].description = data
        } else if index == 18 {
            self.objDiscoverData[3].description = data
        } else {
            self.objDiscoverData[4].description = data
        }
        self.tblInterestList.reloadData()
    }
}
