//
//  Interest_PreferencePresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 20/05/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Interest_PreferencePresentationProtocol {
    func presentSomething()
}

class Interest_PreferencePresenter: Interest_PreferencePresentationProtocol {
    weak var viewController: Interest_PreferenceProtocol?
    var interactor: Interest_PreferenceInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
