//
//  Interest_PreferenceInteractor.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 20/05/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Interest_PreferenceInteractorProtocol {
    func callQuestionaryAPI()
}

protocol Interest_PreferenceDataStore {
    //var name: String { get set }
}

class Interest_PreferenceInteractor: Interest_PreferenceInteractorProtocol, Interest_PreferenceDataStore {
    var presenter: Interest_PreferencePresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callQuestionaryAPI() {
        DefaultLoaderView.sharedInstance.showLoader()
        PreferencesAPI.list(nonce: authToken.nonce, timestamp: Int(authToken.timeStamp)!, token: authToken.token, language: APPLANGUAGE.english, authorization: UserDataModel.authorization) { (response, error) in
            
            delay(0.2) {
                DefaultLoaderView.sharedInstance.hideLoader()
            }
            if response?.responseCode == 200 {
                self.presenter?.getQuestionaryResponse(response : response!)
            } else if response?.responseCode == 203 {
                AppSingleton.sharedInstance().logout()
                AppSingleton.sharedInstance().showAlert((response?.responseMessage!)!, okTitle: "OK")
            } else {
                if error != nil {
                    AppSingleton.sharedInstance().showAlert(kSomethingWentWrong, okTitle: "OK")
                } else {
                    AppSingleton.sharedInstance().showAlert((response?.responseMessage!)!, okTitle: "OK")
                }
            }
            
        }
    }
}
