//
//  InitialLoginPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS216 on 16/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InitialLoginPresentationProtocol {
    func presentSomething()
}

class InitialLoginPresenter: InitialLoginPresentationProtocol {
    weak var viewController: InitialLoginProtocol?
    var interactor: InitialLoginInteractorProtocol?
    
    // MARK: Present something
    func presentSomething() {
        
    }
}
