//
//  BoostPresenter.swift
//  GeekMeets
//
//  Created by SOTSYS124 on 22/04/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BoostPresentationProtocol {
    func callBoostPlansAPI()
    func getBoostPlansResponse(response : BoostGeekResponse)
    
    func callCreateBoostAPI(param : Dictionary<String, String>)
    func getBoostResponse(response : BoostGeekResponse)
    
    func callActiveBoostAPI()
    func getActiveBoostResponse(response : BoostGeekResponse)
}

class BoostPresenter: BoostPresentationProtocol {
    weak var viewController: BoostProtocol?
    var interactor: BoostInteractorProtocol?
    
    // MARK: Present something
    func callBoostPlansAPI(){
        self.interactor?.callBoostPlansAPI()
    }
    func getBoostPlansResponse(response : BoostGeekResponse){
        self.viewController?.getBoostPlansResponse(response: response)
    }
    
    func callCreateBoostAPI(param : Dictionary<String, String>){
        self.interactor?.callCreateBoostAPI(param: param)
    }
    func getBoostResponse(response : BoostGeekResponse){
        self.viewController?.getBoostResponse(response : response)
    }
    
    func callActiveBoostAPI(){
        self.interactor?.callActiveBoostAPI()
    }
    func getActiveBoostResponse(response : BoostGeekResponse){
        self.viewController?.getActiveBoostResponse(response: response)
    }
}
